//! C ABI compatibility layer.
//!
//! Exports `extern "C"` functions with symbol names identical to libxml2 2.x,
//! allowing this library to be used as a binary drop-in replacement via
//! `LD_PRELOAD` or by replacing the system `libxml2.so`.
//!
//! Headers are generated by `cbindgen` via `build.rs` into `include/libxml/`.
//!
//! **Status:** Not yet implemented. Tracking issue: <link to GitHub issue>.
//!
//! # Safety
//!
//! All `extern "C"` functions in this crate are `unsafe` to call from C.
//! Their safety contracts are documented on each function.
#![warn(missing_docs)]
